apiVersion: v1
kind: Pod
metadata:
  name: django-todo-app
  namespace: django-todo-app
spec:
  containers:
  - name: django-todo-app
    image: psharma10394/django-app
    ports:
    - containerPort: 8001
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
